# Generated by Django 2.1.1 on 2018-09-10 03:38

from django.db import migrations, models
import music_player.models
import uuid 

class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='music_player/img')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
