# Generated by Django 2.1.1 on 2018-09-10 06:45

from django.db import migrations, models
import music_player.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0003_auto_20180910_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to=music_player.models.rename_img),
        ),
    ]
