# Generated by Django 2.1.1 on 2018-09-10 07:02

from django.db import migrations, models
import music_player.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0005_auto_20180910_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mp3',
            field=models.FileField(upload_to=music_player.models.rename_mp3),
        ),
        migrations.AlterField(
            model_name='song',
            name='s_author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='song',
            name='s_name',
            field=models.CharField(max_length=50),
        ),
    ]
