# Generated by Django 2.1.1 on 2018-09-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0007_auto_20180912_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='s_uuid',
            field=models.UUIDField(auto_created=True, default='4f0386e4db1047e99b188d47e125f7eb', editable=False, primary_key=True, serialize=False),
        ),
    ]
