# Generated by Django 2.1.1 on 2018-09-12 04:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0008_auto_20180912_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='s_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
