# Generated by Django 2.1.1 on 2018-09-13 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0009_auto_20180912_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_player.song')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_player.user')),
            ],
        ),
    ]
